#!/bin/bash

echo "Deploying BLUE version..."
kubectl apply -f blue_deployment.yaml

echo "Deploying GREEN version..."
kubectl apply -f green_deployment.yaml

echo "Applying Service (currently pointing to GREEN)..."
kubectl apply -f kubeservice.yaml

echo "Waiting for green pod to start..."
sleep 5  # Give it time to boot up

echo "Getting logs from green pod..."
GREEN_POD=$(kubectl get pods -l app=messaging-green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD
