# Generated by Django 5.2.1 on 2025-06-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
